### ISSUE TITLE
Implement multi-track autoplay

### ISSUE THREAD

**Issue by damirkotoric** [Team-Oracy/oracy#1]
When the end of a track is reached:

![image](https://user-images.githubusercontent.com/520622/71494105-a533d900-2898-11ea-8cca-080b4cdade7b.png)

If there is a next track, autoplay it.

Currently the player stops at the end of a track: 

![image](https://user-images.githubusercontent.com/520622/71494124-c5639800-2898-11ea-878e-44d623215662.png)

Meaning currently you cannot listen to a whole audiobook.

Eventually, we'll add ways to browse all available tracks. But for now we can just have it autoplay through all the different tracks.

**Comment by CiprianoFreitas** [comment]
This one is done :)
